Develop Request Licence plugin
DEFRA/sroc-charging-module-api pull request #442
Opened 2021-05-26 14:12 UTC by StuAA78

https://trello.com/c/q3yaHhS7/1982-remove-transactions-v2-licence-level

We have plugins to retrieve and validate bill runs and invoices whenever an endpoint with `bill-runs` and/or `invoices` is hit. The "delete licence" endpoint is the first `licences` endpoint so we develop a similar `RequestLicence` plugin and service to retrieve and validate the requested licence.

Note that this code is very similar to the existing `RequestBillRun` and `RequestInvoice` services and is therefore a prime candidate for refactoring into a base request service with bill run, invoice and licence services that inherit from it; we will consider this for a future PR.

2021-05-26 16:59 UTC, Cruikshanks requested changes
Just a typo in a comment

2021-05-26 16:59 UTC, Cruikshanks commented on app/plugins/request_licence.plugin.js
> + * In this case most of the work is done by the {@module RequestLicednceService}. If licence is found and valid for the
```suggestion
 * In this case most of the work is done by the {@module RequestLicenceService}. If licence is found and valid for the
```

2021-05-26 17:01 UTC, Cruikshanks requested changes
Sorry, also spotted a possible need to change a var name in the test file.

2021-05-27 08:12 UTC, StuAA78 commented on app/plugins/request_licence.plugin.js
> + * In this case most of the work is done by the {@module RequestLicednceService}. If licence is found and valid for the
🤦

2021-05-27 08:12 UTC, StuAA78 commented on test/services/plugins/request_licence.service.test.js
> +  const invoicePath = id => {
Good catch!

2021-05-27 08:43 UTC, Cruikshanks approved these changes

2021-05-27 09:31 UTC, merged