Reject requests with inverted quotation marks
DEFRA/sroc-charging-module-api pull request #492
Opened 2021-07-29 12:12 UTC by Cruikshanks

https://eaflood.atlassian.net/browse/CMEA-11

During initial business acceptance testing of the WRLS system and its integration with the CM API found a transaction file that was rejected by SOP.

This was tracked down to the line description containing 'inverted quotation marks'. It wasn't possible to get an exact example. But based on the description (and Google!) we have interpreted this as

- **“** [Left Double Quotation Mark](https://unicode-table.com/en/201C/) `U+201C`
- **”** [Right Double Quotation Mark](https://unicode-table.com/en/201D/) `U+201D`

This change adds these to our `InvalidCharactersPlugin` which will mean any `POST` request that contains them anywhere in its content will be rejected.

2021-07-29 12:53 UTC, StuAA78 requested changes
Just a tiny note -- the error message and comment could maybe do with being updated to include all the characters we reject?

2021-07-29 14:02 UTC, Cruikshanks commented
![doh](https://user-images.githubusercontent.com/1789650/127505754-60761d0a-46d3-47d0-b8c0-e190d55239e9.gif)

2021-07-29 14:21 UTC, Cruikshanks commented
Not sure why the SonarCloud analysis failed @StuAA78 but it did pass!

<img width="1028" alt="Screenshot 2021-07-29 at 15 20 23" src="https://user-images.githubusercontent.com/1789650/127508826-ccc1dff0-9d13-4e4a-8da6-c19bb9b23db2.png">

2021-07-30 08:08 UTC, StuAA78 approved these changes
![](https://media3.giphy.com/media/3o8doT9BL7dgtolp7O/giphy.gif)

2021-07-30 09:11 UTC, merged