Add database health check controller
DEFRA/sroc-charging-module-api pull request #69
Opened 2020-11-27 11:11 UTC by Cruikshanks

This controller is more about confirming we can connect to a database in a given environment. But it will also allow us to access stats about each table, for example row counts and number of sequential scans. This information will be useful to monitor when the service goes live.

2020-12-01 14:41 UTC, StuAA78 requested changes
As previously discussed we just need to amend the comment in `database_health_check.service.test.js` to not mention the database tables

2020-12-01 14:41 UTC, StuAA78 commented on test/services/database_health_check.service.test.js
> +    // We expect at least the following tables to exist
Comment to be amended as discussed

2020-12-02 09:42 UTC, StuAA78 approved these changes

2020-12-02 13:51 UTC, Cruikshanks commented
Pushing on and merging. It was just resolving a conflict with the merge that caused @StuAA78 approval to be dismissed.

Normally we'd ask for a quick re-approval but poor Stuart still has a slew of PR's in his queue 😳

2020-12-02 13:51 UTC, merged