Migrate calculate charge from SROC to PRESROC
DEFRA/sroc-charging-module-api pull request #87
Opened 2020-12-11 09:06 UTC by Cruikshanks

With the recent announcement that the proposed SROC charge scheme is postponsed until 2021/22 our previous work on implementing an SROC version of the calculate charge controller is not going to be used. It was also our 'best guess' at this time on what would be needed for an SROC calculate charge. With such a delay until the real thing, it is highly likely the implementation will need to change anyway.

But we do still need a PRESROC calculate charge and my migrating the functionality over it means it doesn't go to waste!

So these changes migrate the existing functionality for a calculate charge endpoint to work for PRESROC based requests instead 😀

2020-12-13 22:50 UTC, Cruikshanks commented
Apologies @StuAA78 this looks crazy! 😳 😳 😳 

The good news is there is actually just a lot of file movements and renaming, some deletions, and a bunch of comments that make it appear made. The actual line diff isn't _too crazy_.

<img width="128" alt="Screenshot 2020-12-13 at 22 47 53" src="https://user-images.githubusercontent.com/1789650/102026388-7195db80-3d95-11eb-9e44-ebc595f42abe.png">

But I would say that as I'm not the one who is being asked to review it.

More than happy to jump on a call and give a walkthrough / pair on the review if that will help. 🙇

2020-12-14 09:50 UTC, StuAA78 commented on test/support/helpers/general.helper.js
> +    return JSON.parse(JSON.stringify(thingToBeCloned))
We can replace this with `Hoek.clone`: https://github.com/hapijs/hoek/blob/master/API.md

2020-12-14 11:48 UTC, StuAA78 requested changes
As discussed we can change `cloneObject` to use Hoek, all looks good other than that 😁

2020-12-14 16:43 UTC, StuAA78 approved these changes
![](https://media4.giphy.com/media/oGO1MPNUVbbk4/giphy.gif)

2020-12-14 17:08 UTC, merged